PIDEV/src/Entity/Outils.php
<?php

namespace App\Entity;

use App\Repository\OutilsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Mime\Message; 
use Symfony\Component\Validator\Constraints as Assert; 


#[ORM\Entity(repositoryClass: OutilsRepository::class)]
class Outils
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;
  
    
    #[ORM\Column(length: 255)] 
    #[Assert\NotBlank(message:"le champ est obligatoire")]
    private ?string $label_out = null;

    #[ORM\Column] 
    #[Assert\NotBlank(message:"le champ est obligatoire")] 
    #[Assert\Range(
        min: 1,
        max: 100,
        notInRangeMessage: 'Vous devez être entre {{ min }} et {{ max }} ',
    )]
    private ?int $quantite = null;

    #[ORM\Column(length: 255)] 
    private ?string $image = null;

    #[ORM\ManyToOne(inversedBy: 'outil')]
    private ?Reservation $reservations = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabelOut(): ?string
    {
        return $this->label_out;
    }

    public function setLabelOut(string $label_out): self
    {
        $this->label_out = $label_out;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getReservations(): ?Reservation
    {
        return $this->reservations;
    }

    public function setReservations(?Reservation $reservations): self
    {
        $this->reservations = $reservations;

        return $this;
    }
}

PIDEV/src/Form/OutilsType.php
<?php

namespace App\Form;

use App\Entity\Outils;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;


class OutilsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('label_out')
            ->add('quantite')
            ->add('imageFile', FileType::class,[
                'mapped' => false ])
            //->add('reservations')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Outils::class,
        ]);
    }
}

PIDEV/src/Controller/OutilsController.php
<?php

namespace App\Controller;

use App\Entity\Outils;
use App\Entity\Urlizer;
use App\Form\OutilsType;
use App\Repository\OutilsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


#[Route('/outils')]
class OutilsController extends AbstractController
{
    #[Route('/', name: 'app_outils_index', methods: ['GET'])]
    public function index(OutilsRepository $outilsRepository): Response
    {
        return $this->render('outils/index.html.twig', [
            'outils' => $outilsRepository->findAll(),
        ]);
    }
    #[Route('/front', name: 'app_outils_indexfront', methods: ['GET'])]
    public function indexfront(OutilsRepository $outilsRepository): Response
    {
        return $this->render('outils/indexfront.html.twig', [
            'outils' => $outilsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_outils_new', methods: ['GET', 'POST'])]
    public function new(Request $request, OutilsRepository $outilsRepository): Response
    {
        $outil = new Outils();
        $form = $this->createForm(OutilsType::class, $outil);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $uploadedFile */
            $uploadedFile = $form['imageFile']->getData();
            $destination = $this->getParameter('kernel.project_dir').'/public/uploads';
            $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
            $newFilename = Urlizer::urlize($originalFilename).'-'.uniqid().'.'.$uploadedFile->guessExtension();
            $uploadedFile->move(
                $destination,
                $newFilename
            );
            $outil->setImage($newFilename);
            $outilsRepository->save($outil, true);

            return $this->redirectToRoute('app_outils_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('outils/new.html.twig', [
            'outil' => $outil,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_outils_show', methods: ['GET'])]
    public function show(Outils $outil): Response
    {
        return $this->render('outils/show.html.twig', [
            'outil' => $outil,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_outils_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Outils $outil, OutilsRepository $outilsRepository): Response
    {
        $form = $this->createForm(OutilsType::class, $outil);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $uploadedFile */
            $uploadedFile = $form['imageFile']->getData();
            $destination = $this->getParameter('kernel.project_dir').'/public/uploads';
            $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
            $newFilename = Urlizer::urlize($originalFilename).'-'.uniqid().'.'.$uploadedFile->guessExtension();
            $uploadedFile->move(
                $destination,
                $newFilename
            );
                $outil->setImage($newFilename);
            $outilsRepository->save($outil, true);

            return $this->redirectToRoute('app_outils_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('outils/edit.html.twig', [
            'outil' => $outil,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_outils_delete', methods: ['POST'])]
    public function delete(Request $request, Outils $outil, OutilsRepository $outilsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$outil->getId(), $request->request->get('_token'))) {
            $outilsRepository->remove($outil, true);
        }

        return $this->redirectToRoute('app_outils_index', [], Response::HTTP_SEE_OTHER);
    }
}

PIDEV/templates/outils/_delete_form.html.twig
<form method="post" action="{{ path('app_outils_delete', {'id': outil.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ outil.id) }}">
    <button class="btn">Delete</button>
</form>

PIDEV/templates/outils/_form.html.twig
{{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}
{{ form_label(form.label_out,"Nom outil") }} 
    {{ form_widget(form.label_out,{'attr': {'class':'form-control'}}) }} 
     {{ form_errors(form.label_out) }} 

     {{ form_label(form.quantite,"Quantite") }} 
    {{ form_widget(form.quantite,{'attr': {'class':'form-control'}}) }} 
     {{ form_errors(form.quantite) }}   
   
   {{ form_label(form.imageFile,"image outil") }}  
       {{ form_widget(form.imageFile,{'attr': {'class':'form-control'}}) }}  
          {{ form_errors(form.imageFile) }}   
    
 <button class="btn">{{ button_label|default('Create') }}</button>
     {{ form_end(form) }}

   
   

PIDEV/templates/outils/edit.html.twig
{% extends 'backtemplate/outilsback.html.twig'%}
{% block title %}edit Outils {% endblock %}

{% block body %}
    <h1>Edit Outils</h1>

    {{ include('outils/_form.html.twig', {'button_label': 'Update'}) }}
    {{ include('outils/_delete_form.html.twig') }}

    <a  class="btn" href="{{ path('app_outils_index') }}">back to list</a>

    
{% endblock %}

PIDEV/templates/outils/index.html.twig
{% extends 'backtemplate/outilsback.html.twig'%}

{% block title%}Outils index {%endblock%}

{% block body %}
    <h1>Outils</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Label_out</th>
                <th>Quantite</th>
                <th>Image</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for outil in outils %}
            <tr>
                <td>{{ outil.id }}</td>
                <td>{{ outil.labelOut }}</td>
                <td>{{ outil.quantite }}</td>
                <td><img id="img"  class="card-img-top img-fluid" style="height: 150px; width:250px;" src="/uploads/{{outil.image}}"></td>
                <td>
                    <a class= "btn" href="{{ path('app_outils_show', {'id': outil.id}) }}">show</a>
                    <a class= "btn" href="{{ path('app_outils_edit', {'id': outil.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class= "btn" href="{{ path('app_outils_new') }}">Create new</a>
{% endblock %}

PIDEV/templates/outils/indexfront.html.twig
{% extends 'fronttemplate/basefront.html.twig' %}

{% block title %}Outils
{% endblock %}
{% block body %}
<style>
		.wrapper{
			width:1100px;
			display: grid;
			grid-template-columns: repeat(3, 1fr);
			grid-auto-rows: auto;
			grid-gap: 20px;	
			
		}
		p{
				font-size:14px;
			}
		
	</style>
	<div class="wrapper">

		{% for outil in outils %}
		
			<div class="card" style="width: 20rem;">
            <div class="position-relative">
									<img class="card-img-top" style="height: 230px; width:320px;" src="{{asset('uploads/') ~ outil.image}}" alt="Card image cap">
									
								</div>
				
				 <div class="card-body">
				 <h4 class="card-title">{{ outil.quantite }}</h4>
				<p class="description">{{ outil.labelOut }} </p>
				


				
				
    
				</div>
                <a class="stretched-link" href="{{ path('app_reservation_new') }}"></a>
			</div>

		{% else %}
				<div colspan="4">no records found</div>
		{% endfor %}

	</div>

	

</div>

	</div>



{% endblock %}

PIDEV/templates/outils/new.html.twig
{% extends 'backtemplate/outilsback.html.twig'%}
{% block title %} New Outils {% endblock %}

{% block body %}
    <h1>Create new Outils</h1>

    {{ include('outils/_form.html.twig') }} 

    
    <a href="{{ path('app_outils_index') }}">back to list</a>
{% endblock %}

PIDEV/templates/outils/show.html.twig
{% extends 'backtemplate/outilsback.html.twig'%}
{% block title %} Outils {% endblock %}

{% block body %}
    <h1>Outils</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ outil.id }}</td>
            </tr>
            <tr>
                <th>Label_out</th>
                <td>{{ outil.labelOut }}</td>
            </tr>
            <tr>
                <th>Quantite</th>
                <td>{{ outil.quantite }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td><img id="img"  class="card-img-top img-fluid" style="height: 150px; width:250px;" src="/uploads/{{outil.image}}"></td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_outils_index') }}">back to list</a>

    <a href="{{ path('app_outils_edit', {'id': outil.id}) }}">edit</a>

    {{ include('outils/_delete_form.html.twig') }}
{% endblock %}